version: 2
updates:
  allow:
    - dependency-type: all
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    reviewers:
      - "dastrobu"
    assignees:
      - "dastrobu"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "dastrobu"
    assignees:
      - "dastrobu"