# GoReleaser configuration for mail-mcp
# https://goreleaser.com

version: 2

# Project metadata
project_name: mail-mcp

# Build configuration
builds:
  - id: mail-mcp
    main: .
    binary: mail-mcp

    # macOS only (Mail.app dependency)
    goos:
      - darwin

    goarch:
      - amd64
      - arm64

    # Build flags
    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

    env:
      - CGO_ENABLED=1

# Archive configuration
archives:
  - id: mail-mcp
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Homebrew tap (using modern 'homebrew' instead of deprecated 'brews')
brews:
  - repository:
      owner: dastrobu
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    directory: Formula

    homepage: https://github.com/dastrobu/mail-mcp
    description: "MCP server providing programmatic access to macOS Mail.app"

    license: MIT

    # Only macOS
    dependencies:
      - name: go
        type: build

    test: |
      system "#{bin}/mail-mcp", "--version"

    install: |
      bin.install "mail-mcp"

    service: |
      run [opt_bin/"mail-mcp", "run", "--transport=http"]
      keep_alive true
      log_path var/"log/mail-mcp.log"
      error_log_path var/"log/mail-mcp.err"
      environment_variables APPLE_MAIL_MCP_PORT: "8787", APPLE_MAIL_MCP_HOST: "localhost"

    caveats: |
      Apple Mail MCP Server has been installed!

      ⚠️  IMPORTANT: For proper automation permissions, you should run this server
      via launchd or brew services (not from Terminal directly).

      Option 1: Use Homebrew Services (Standard)
        brew services start mail-mcp

      Option 2: Use custom launchd service (for custom port/debug)
        mail-mcp launchd create

      To remove the launchd service:
        mail-mcp launchd remove

      Before uninstalling with 'brew uninstall mail-mcp':
        1. Stop and remove the service: brew services stop mail-mcp OR mail-mcp launchd remove
        2. Then run: brew uninstall mail-mcp

      For more information:
        • README: https://github.com/dastrobu/mail-mcp#readme
        • Docs: https://github.com/dastrobu/mail-mcp/tree/main/docs

# Release configuration
release:
  github:
    owner: dastrobu
    name: mail-mcp

  draft: false
  prerelease: auto

  name_template: "v{{ .Version }}"

  # Appends the changelog to the release body
  mode: append

  footer: |
    ---

    ## 📦 Installation

    ### Homebrew (Recommended)

    ```bash
    brew tap dastrobu/tap
    brew install mail-mcp
    ```

    ### Binary Download

    Download the appropriate archive for your system:
    - **Intel Mac**: `mail-mcp_{{ .Version }}_darwin_amd64.tar.gz`
    - **Apple Silicon**: `mail-mcp_{{ .Version }}_darwin_arm64.tar.gz`

    Extract and install:
    ```bash
    tar -xzf mail-mcp_{{ .Version }}_darwin_*.tar.gz
    sudo mv mail-mcp /usr/local/bin/
    ```

    ### From Source

    ```bash
    go install github.com/dastrobu/mail-mcp@v{{ .Version }}
    ```

    ## 📚 Documentation

    See the [README](https://github.com/dastrobu/mail-mcp#readme) for usage instructions.

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"